- hosts: deploy
  roles:
  - default-storage
  vars:
    storage:
      nfs:
        #nfs service
        server: "127.0.0.1"
        #nfs path
        server_path: "/nfs-data"
        #storage_class 以后pvc申请会使用,每个nfs实例都要区分名字
        storage_class: "storage-class-nfs-default"
        #每个nfs实例都要区分名字
        provisioner_name: "nfs-provisioner-nfs-default"
