- hosts: deploy
  roles:
  - cluster-storage
  vars_prompt:
  - name: "prompt"
    prompt: "请确认 nfs 相关配置已经更新在本文件vars部分？, all in one 版本可以忽略该配置 [yes/no] 默认为："
    private: no
    default: "no"
  vars:
    storage:
      nfs:
        #需要手动打开
        enabled: "yes"
        #nfs service
        server: "10.19.0.199"
        #nfs path
        server_path: "/nfs-data"
      aliyun_nas:
        enabled: "no"
        server: "xxxxxxxxxxx.cn-hangzhou.nas.aliyuncs.com"
        server_path: "/"
        storage_class: "storage-aliyun-class-test"
        provisioner_name: "nfs-provisioner-aliyun-test"
