apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: factor-12
spec:
  selector:
    matchLabels:
      app: factor-12
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: factor-12
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      volumes:
      - name: log
        emptyDir: {}
      - name: nfs-log
        nfs:
          path: /nfs-data
          server: 192.168.3.16
      containers:
      - name: factor-12
        image: docker.mxnavi.com/inter-system/12factor
        volumeMounts:
        - name: log
          mountPath: /daigong-1
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 0.5
        command:
        - /start.sh
        ports:
        - containerPort: 80
