apiVersion: v1
kind: Service
metadata:
  name: to-marathon-sy
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: to-marathon-sy
subsets:
  - addresses:
    - ip: 192.168.3.24
    ports:
    - port: 80
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: to-marathon-sy
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  rules:
  - host: '*-sy.mxnavi.com'
    http:
      paths:
      - backend:
          serviceName: to-marathon-sy
          servicePort: 80
