---
kind: Service
apiVersion: v1
metadata:
  name: service-a
spec:
  ports:
    - port: 8000
      name: http
  selector:
    app: service-a
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: service-a
spec:
  rules:
  - host: service-a.demo.k8s-project.mxnavi.com
    http:
      paths:
      - backend:
          serviceName: service-a
          servicePort: 8000
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: service-a
spec:
  selector:
    matchLabels:
      app: service-a
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: service-a
        version: "1"
    spec:
      containers:
      - name: app
        image: docker.mxnavi.com/k8s/k8s_test_server:1.0
        command:
        - /start.sh
        env:
        - name: time
          value: "0"
        ports:
        - containerPort: 8000
