- name: 建立nginx ingress 目录
  shell: mkdir -p {{ base_dir }}/manifests/nginx-ingress/nginx-ingress
  ignore_errors: true

- name: 下载nginx ingress helm package
  copy: src=nginx-ingress/ dest={{ base_dir }}/manifests/nginx-ingress/nginx-ingress

- name: 下载nginx ingress values
  template: src=values.yaml.j2 dest={{ base_dir }}/manifests/nginx-ingress/values.yaml

- name: helm 安装 nginx ingress
  shell: "{{ bin_dir }}/helm install --namespace nginx-ingress --name nginx-ingress --values {{ base_dir }}/manifests/nginx-ingress/values.yaml {{ base_dir }}/manifests/nginx-ingress/nginx-ingress"

- name: 非multi-master安装方式，deploy master机器作为nginx主机
  shell: "{{ bin_dir }}/kubectl label nodes {{ inventory_hostname }} role=nginx-ingress --overwrite=true"
  delegate_to: "{{ groups.deploy[0] }}"
  when: DEPLOY_MODE != "multi-master"

- name: multi-master安装方式，需要定义独享的nginx节点
  shell: "{{ bin_dir }}/kubectl label nodes {{ inventory_hostname }} role=nginx-ingress --overwrite=true"
  delegate_to: "{{ groups.nginx[0] }}"
  when: DEPLOY_MODE == "multi-master"
