- hosts: deploy
  roles:
  - nginx-ingress
  vars:
    controller_image_repository: docker.mxnavi.com/k8s/nginx-ingress-controller
    controller_image_tag: 0.19.0
    defaultBackend_image_repository: docker.mxnavi.com/k8s/defaultbackend-amd64
    defaultBackend_image_tag: 1.5
